# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyForceSense.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyForceSenseWidget(object):
    def setupUi(self, PyForceSenseWidget):
        PyForceSenseWidget.setObjectName("PyForceSenseWidget")
        PyForceSenseWidget.resize(640, 480)
        self.curForceLabel = QtWidgets.QLabel(PyForceSenseWidget)
        self.curForceLabel.setGeometry(QtCore.QRect(27, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.curForceLabel.setFont(font)
        self.curForceLabel.setStyleSheet("background-color: rgb(46, 255, 53)")
        self.curForceLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.curForceLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.curForceLabel.setLineWidth(3)
        self.curForceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curForceLabel.setObjectName("curForceLabel")
        self.maxForceLabel = QtWidgets.QLabel(PyForceSenseWidget)
        self.maxForceLabel.setGeometry(QtCore.QRect(147, 140, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.maxForceLabel.setFont(font)
        self.maxForceLabel.setStyleSheet("background-color: rgb(255, 78, 81)")
        self.maxForceLabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.maxForceLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.maxForceLabel.setLineWidth(3)
        self.maxForceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.maxForceLabel.setObjectName("maxForceLabel")
        self.serialOutputText = QtWidgets.QPlainTextEdit(PyForceSenseWidget)
        self.serialOutputText.setGeometry(QtCore.QRect(350, 10, 271, 231))
        self.serialOutputText.setReadOnly(True)
        self.serialOutputText.setObjectName("serialOutputText")
        self.forcePlot = PlotWidget(PyForceSenseWidget)
        self.forcePlot.setGeometry(QtCore.QRect(20, 260, 601, 201))
        self.forcePlot.setObjectName("forcePlot")
        self.resetMaxBtn = QtWidgets.QPushButton(PyForceSenseWidget)
        self.resetMaxBtn.setGeometry(QtCore.QRect(250, 140, 81, 21))
        self.resetMaxBtn.setObjectName("resetMaxBtn")
        self.comportCombo = QtWidgets.QComboBox(PyForceSenseWidget)
        self.comportCombo.setGeometry(QtCore.QRect(20, 10, 211, 28))
        self.comportCombo.setObjectName("comportCombo")
        self.connectButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.connectButton.setGeometry(QtCore.QRect(240, 10, 91, 29))
        self.connectButton.setObjectName("connectButton")
        self.logButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.logButton.setGeometry(QtCore.QRect(20, 90, 311, 31))
        self.logButton.setObjectName("logButton")
        self.logName = QtWidgets.QLineEdit(PyForceSenseWidget)
        self.logName.setGeometry(QtCore.QRect(20, 60, 211, 27))
        self.logName.setObjectName("logName")
        self.autoNameButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.autoNameButton.setGeometry(QtCore.QRect(240, 60, 91, 29))
        self.autoNameButton.setObjectName("autoNameButton")
        self.resetTareButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.resetTareButton.setGeometry(QtCore.QRect(250, 160, 81, 21))
        self.resetTareButton.setObjectName("resetTareButton")
        self.clearButton = QtWidgets.QPushButton(PyForceSenseWidget)
        self.clearButton.setGeometry(QtCore.QRect(350, 240, 271, 21))
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(PyForceSenseWidget)
        QtCore.QMetaObject.connectSlotsByName(PyForceSenseWidget)

    def retranslateUi(self, PyForceSenseWidget):
        _translate = QtCore.QCoreApplication.translate
        PyForceSenseWidget.setWindowTitle(_translate("PyForceSenseWidget", "Form"))
        self.curForceLabel.setText(_translate("PyForceSenseWidget", "0"))
        self.maxForceLabel.setText(_translate("PyForceSenseWidget", "0"))
        self.resetMaxBtn.setText(_translate("PyForceSenseWidget", "Reset Max"))
        self.connectButton.setText(_translate("PyForceSenseWidget", "Connect"))
        self.logButton.setText(_translate("PyForceSenseWidget", "Start logging"))
        self.logName.setText(_translate("PyForceSenseWidget", "LogFile.txt"))
        self.autoNameButton.setText(_translate("PyForceSenseWidget", "Auto Name"))
        self.resetTareButton.setText(_translate("PyForceSenseWidget", "Reset Tare"))
        self.clearButton.setText(_translate("PyForceSenseWidget", "Clear"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PyForceSenseWidget = QtWidgets.QWidget()
    ui = Ui_PyForceSenseWidget()
    ui.setupUi(PyForceSenseWidget)
    PyForceSenseWidget.show()
    sys.exit(app.exec_())
